project_id = "zdrcjhohalgzhlbufwcl"

[api]
enabled = true
port = "54321"
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = "54322"

[studio]
enabled = true
port = "54323"

[inbucket]
enabled = true
port = "54324"
smtp_port = "54325"
pop3_port = "54326"

[storage]
enabled = true
port = "54327"
image_transformation.enabled = true

[auth]
enabled = true
port = "54328"
site_url = "http://localhost:3000"
additional_redirect_urls = []

[functions]
verify_jwt = false

[functions.bright-action]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = false

[functions.gemini-voice-chat]
verify_jwt = false